// <auto-generated />
namespace TpIngSoftII.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Proyecto_ABM_Ejemplo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Proyecto_ABM_Ejemplo));
        
        string IMigrationMetadata.Id
        {
            get { return "202009030011594_Proyecto_ABM_Ejemplo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
